// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/Shopify/sarama"
	"github.com/seibert-media/go-kafka/persistent"
)

type PersistentOffsetManager struct {
	HandleMessageStub        func(int32, *sarama.ConsumerMessage) error
	handleMessageMutex       sync.RWMutex
	handleMessageArgsForCall []struct {
		arg1 int32
		arg2 *sarama.ConsumerMessage
	}
	handleMessageReturns struct {
		result1 error
	}
	handleMessageReturnsOnCall map[int]struct {
		result1 error
	}
	NextOffsetStub        func(int32) (int64, error)
	nextOffsetMutex       sync.RWMutex
	nextOffsetArgsForCall []struct {
		arg1 int32
	}
	nextOffsetReturns struct {
		result1 int64
		result2 error
	}
	nextOffsetReturnsOnCall map[int]struct {
		result1 int64
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *PersistentOffsetManager) HandleMessage(arg1 int32, arg2 *sarama.ConsumerMessage) error {
	fake.handleMessageMutex.Lock()
	ret, specificReturn := fake.handleMessageReturnsOnCall[len(fake.handleMessageArgsForCall)]
	fake.handleMessageArgsForCall = append(fake.handleMessageArgsForCall, struct {
		arg1 int32
		arg2 *sarama.ConsumerMessage
	}{arg1, arg2})
	fake.recordInvocation("HandleMessage", []interface{}{arg1, arg2})
	fake.handleMessageMutex.Unlock()
	if fake.HandleMessageStub != nil {
		return fake.HandleMessageStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.handleMessageReturns
	return fakeReturns.result1
}

func (fake *PersistentOffsetManager) HandleMessageCallCount() int {
	fake.handleMessageMutex.RLock()
	defer fake.handleMessageMutex.RUnlock()
	return len(fake.handleMessageArgsForCall)
}

func (fake *PersistentOffsetManager) HandleMessageCalls(stub func(int32, *sarama.ConsumerMessage) error) {
	fake.handleMessageMutex.Lock()
	defer fake.handleMessageMutex.Unlock()
	fake.HandleMessageStub = stub
}

func (fake *PersistentOffsetManager) HandleMessageArgsForCall(i int) (int32, *sarama.ConsumerMessage) {
	fake.handleMessageMutex.RLock()
	defer fake.handleMessageMutex.RUnlock()
	argsForCall := fake.handleMessageArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *PersistentOffsetManager) HandleMessageReturns(result1 error) {
	fake.handleMessageMutex.Lock()
	defer fake.handleMessageMutex.Unlock()
	fake.HandleMessageStub = nil
	fake.handleMessageReturns = struct {
		result1 error
	}{result1}
}

func (fake *PersistentOffsetManager) HandleMessageReturnsOnCall(i int, result1 error) {
	fake.handleMessageMutex.Lock()
	defer fake.handleMessageMutex.Unlock()
	fake.HandleMessageStub = nil
	if fake.handleMessageReturnsOnCall == nil {
		fake.handleMessageReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.handleMessageReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *PersistentOffsetManager) NextOffset(arg1 int32) (int64, error) {
	fake.nextOffsetMutex.Lock()
	ret, specificReturn := fake.nextOffsetReturnsOnCall[len(fake.nextOffsetArgsForCall)]
	fake.nextOffsetArgsForCall = append(fake.nextOffsetArgsForCall, struct {
		arg1 int32
	}{arg1})
	fake.recordInvocation("NextOffset", []interface{}{arg1})
	fake.nextOffsetMutex.Unlock()
	if fake.NextOffsetStub != nil {
		return fake.NextOffsetStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.nextOffsetReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *PersistentOffsetManager) NextOffsetCallCount() int {
	fake.nextOffsetMutex.RLock()
	defer fake.nextOffsetMutex.RUnlock()
	return len(fake.nextOffsetArgsForCall)
}

func (fake *PersistentOffsetManager) NextOffsetCalls(stub func(int32) (int64, error)) {
	fake.nextOffsetMutex.Lock()
	defer fake.nextOffsetMutex.Unlock()
	fake.NextOffsetStub = stub
}

func (fake *PersistentOffsetManager) NextOffsetArgsForCall(i int) int32 {
	fake.nextOffsetMutex.RLock()
	defer fake.nextOffsetMutex.RUnlock()
	argsForCall := fake.nextOffsetArgsForCall[i]
	return argsForCall.arg1
}

func (fake *PersistentOffsetManager) NextOffsetReturns(result1 int64, result2 error) {
	fake.nextOffsetMutex.Lock()
	defer fake.nextOffsetMutex.Unlock()
	fake.NextOffsetStub = nil
	fake.nextOffsetReturns = struct {
		result1 int64
		result2 error
	}{result1, result2}
}

func (fake *PersistentOffsetManager) NextOffsetReturnsOnCall(i int, result1 int64, result2 error) {
	fake.nextOffsetMutex.Lock()
	defer fake.nextOffsetMutex.Unlock()
	fake.NextOffsetStub = nil
	if fake.nextOffsetReturnsOnCall == nil {
		fake.nextOffsetReturnsOnCall = make(map[int]struct {
			result1 int64
			result2 error
		})
	}
	fake.nextOffsetReturnsOnCall[i] = struct {
		result1 int64
		result2 error
	}{result1, result2}
}

func (fake *PersistentOffsetManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.handleMessageMutex.RLock()
	defer fake.handleMessageMutex.RUnlock()
	fake.nextOffsetMutex.RLock()
	defer fake.nextOffsetMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *PersistentOffsetManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ persistent.OffsetManager = new(PersistentOffsetManager)
